#!/usr/bin/env bash

# systemd Service Installer Script

# Directory of this script (absolute path)
DIR=$(dirname $(realpath $0))

service="tokens-api"

# user=$USER # by default run service as user who's installing
user="root" # run service as root (need access to letsencrypt certs and port 443)

# override default user from argument to install command (if supplied)
if [ "$1" == "install" ]; then
  [ -n "$2" ] && user=$2
fi

service_file="[Unit]
Description=Web API – Tokens for Climate Care
Documentation=https://github.com/studioprocess/tokens-api-node
After=network.target couchdb.service
Wants=couchdb.service
Conflicts=

[Service]
Environment=
Type=simple
User=$user
ExecStart=$DIR/main.mjs
WorkingDirectory=$DIR
Restart=always

[Install]
WantedBy=multi-user.target
"

usage() {
  echo "Usage:"
  echo "  Install/Uninstall:  $0 install|remove|uninstall"
  echo "  Enable/Disable:     $0 enable|disable"
  echo "  Start/Stop/Restart: $0 start|stop|restart"
  echo "  Status:             $0 status"
  echo "  Logs:               $0 logs [live]"
  echo "  Reload Certificate: $0 reload-cert"
  exit
}

if [ $# -eq 0 ]; then
  usage
fi

if [ $1 == "install" ] ; then
  echo "[ Installing Script to /usr/local/bin ]"
  sudo ln -sf $(realpath $0) /usr/local/bin/$(basename $0)
  echo "[ Installing Service File ]"
  echo "$service_file" | sudo tee /etc/systemd/system/${service}.service > /dev/null
  echo "[ Enabling Service ]"
  sudo systemctl enable $service
  echo "Important: Service will be run as user: $user"
elif [ $1 == "remove" ] || [ $1 == "uninstall" ]; then
  echo "[ Disabling Service ]"
  sudo systemctl disable $service
  echo "[ Removing Service File ]"
  sudo rm -f /etc/systemd/system/${service}.service
  echo "[ Removing Script from /usr/local/bin ]"
  sudo rm /usr/local/bin/$(basename $0)
elif [ $1 == "enable" ] ; then
  echo "[ Enabling Service ]"
  sudo systemctl enable $service
elif [ $1 == "disable" ] ; then
  echo "[ Disabling Service ]"
  sudo systemctl disable $service
elif [ $1 == "start" ] ; then
  echo "[ Starting Service ]"
  sudo systemctl start $service
elif [ $1 == "stop" ] ; then
  echo "[ Stopping Service ]"
  sudo systemctl stop $service
elif [ $1 == "restart" ] ; then
  echo "[ Restarting Service ]"
  sudo systemctl restart $service
elif [ $1 == "status" ] ; then
  echo "[ Service Service ]"
  sudo systemctl status $service
elif [ $1 == "logs" ] ; then
  echo "[ Service Logs ]"
  if [ "$2" == "live" ]; then
      sudo journalctl -u ${service}.service -e -f
    else
      sudo journalctl -u ${service}.service -e
    fi
elif [ $1 == "reload-cert" ] ; then
  echo "[ Reload Certificate ]"
  sudo systemctl kill $service --signal=SIGUSR2
else
  usage
fi
